# Generated by Django 3.1.1 on 2020-09-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='greedisgood', max_length=20),
        ),
    ]
