# Generated by Django 3.1.1 on 2020-09-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.RenameField(
            model_name='userinventory',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='userinventory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='repetitive_login',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GameReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.game')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.item')),
            ],
            options={
                'db_table': 'gamereward',
            },
        ),
        migrations.CreateModel(
            name='DailyLoginReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.item')),
            ],
            options={
                'db_table': 'dailyloginreward',
            },
        ),
        migrations.CreateModel(
            name='DailyLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.user')),
            ],
            options={
                'db_table': 'dailylogin',
            },
        ),
    ]
