# Generated by Django 3.1.1 on 2020-09-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200918_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='greedisgood', max_length=255),
            preserve_default=False,
        ),
    ]
